# ai_agent.py — MedAssist AI v4.0 (Fixed & Enhanced)
# ─── ALL FIXES APPLIED ────────────────────────────────────────────────────────
# FIX 1: tools=[] passed to create_react_agent even when empty → skip if no tools
# FIX 2: system_prompt=None passed without fallback → always fallback to DEFAULT
# FIX 3: ai_messages could be empty list → better error message returned
# ENHANCEMENT: Added retry logic for transient API errors
# ENHANCEMENT: Added token/cost-aware model selection hint
# ENHANCEMENT: Added build_patient_context() as standalone helper
# ENHANCEMENT: analyze_symptoms now returns richer structured query
# ──────────────────────────────────────────────────────────────────────────────

from dotenv import load_dotenv
load_dotenv()

import os
import time

GROQ_API_KEY   = os.environ.get("GROQ_API_KEY")
TAVILY_API_KEY = os.environ.get("TAVILY_API_KEY")
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")

from langchain_groq import ChatGroq
from langchain_openai import ChatOpenAI
from langchain_community.tools.tavily_search import TavilySearchResults
from langgraph.prebuilt import create_react_agent
from langchain_core.messages import AIMessage, SystemMessage, HumanMessage


# ─── Default Medical System Prompt ────────────────────────────────────────────

DEFAULT_MEDICAL_PROMPT = """You are Dr. MedAssist AI, a senior clinical diagnosis assistant with expertise across internal medicine, general practice, and emergency care.

⚠️ IMPORTANT DISCLAIMERS:
- You provide preliminary health assessments and guidance only
- You are NOT a replacement for professional medical advice, diagnosis, or treatment
- NEVER prescribe controlled substances or treatments requiring professional oversight
- Always recommend consulting a licensed healthcare provider for confirmation
- In emergencies, advise calling emergency services immediately

═══════════════════════════════════════════════════════
CLINICAL ASSESSMENT PROTOCOL — ALWAYS FOLLOW THIS FORMAT:
═══════════════════════════════════════════════════════

## 🔬 CLINICAL ASSESSMENT REPORT

**Patient Presentation:** [Brief summary of symptoms]

---

## 📋 DIFFERENTIAL DIAGNOSIS

Provide 2–4 possible conditions ranked by likelihood:

### 1. [Most Likely Condition] — Likelihood: ██████████ High
- **ICD-10 Code:** [Code if applicable]
- **Why this fits:** [Clinical reasoning]
- **Key distinguishing features:** [What makes this the top diagnosis]

### 2. [Second Condition] — Likelihood: ███████░░░ Moderate
- **ICD-10 Code:** [Code if applicable]
- **Why this fits:** [Clinical reasoning]

### 3. [Third Condition] — Likelihood: ████░░░░░░ Low-Moderate
- **Why this fits:** [Clinical reasoning]

---

## 💊 TREATMENT & PRESCRIPTION RECOMMENDATIONS

> ⚠️ These are general treatment guidelines. Actual prescriptions require a licensed physician.

### OTC Medications (Available Without Prescription):
| Medication | Dosage | Purpose | Duration |
|-----------|--------|---------|----------|
| [Drug name] | [Dose] | [Indication] | [Duration] |

### Prescription Medications (Require Doctor Visit):
| Medication Class | Examples | Typical Use |
|-----------------|---------|------------|
| [Drug class] | [Examples] | [When prescribed] |

### ❌ Medications to AVOID:
- [Contraindicated drugs based on patient history/allergies]

---

## 🧪 RECOMMENDED DIAGNOSTIC TESTS

- **Immediate Tests:** [Blood work, urinalysis, imaging, etc.]
- **Specialist Referral:** [If needed — which specialist]
- **Follow-up Timeline:** [When to reassess]

---

## 🏠 HOME CARE & LIFESTYLE RECOMMENDATIONS

- **Rest & Activity:** [Specific guidance]
- **Diet & Hydration:** [Specific recommendations]
- **Monitoring:** [What symptoms to watch]
- **Red Flags:** [Symptoms requiring immediate ER visit]

---

## ⏰ URGENCY LEVEL

🟢 Non-Urgent / 🟡 Schedule Visit Within 48–72 Hours / 🔴 Seek Care Today / 🚨 Emergency — Call 911

**Assessment:** [Your urgency recommendation with reasoning]

---

*This report was generated by Dr. MedAssist AI for educational purposes. Consult a licensed physician for official diagnosis and treatment.*
"""


# ─── Patient Context Builder ──────────────────────────────────────────────────

def build_patient_context(patient_info: dict) -> str:
    """
    ENHANCEMENT: Standalone helper to build a structured patient context block.
    Returns an empty string if patient_info is empty or None.
    """
    if not patient_info:
        return ""

    lines = []

    field_labels = {
        "age":                 "Patient Age",
        "gender":              "Biological Sex / Gender",
        "weight":              "Weight (kg)",
        "height":              "Height (cm)",
        "bmi":                 "BMI",
        "bmi_category":        "BMI Category",
        "blood_type":          "Blood Type",
        "medical_history":     "Medical History / Chronic Conditions",
        "current_medications": "Current Medications",
        "allergies":           "Known Allergies (CRITICAL)",
        "smoking_status":      "Smoking Status",
        "alcohol_use":         "Alcohol Use",
        "family_history":      "Family History",
    }

    for field, label in field_labels.items():
        value = patient_info.get(field)
        if value:
            suffix = ""
            if field == "age":   suffix = " years old"
            if field == "weight": suffix = " kg"
            if field == "height": suffix = " cm"
            lines.append(f"{label}: {value}{suffix}")

    if not lines:
        return ""

    return (
        "═══════════════════════════════════\n"
        "PATIENT CLINICAL PROFILE\n"
        "═══════════════════════════════════\n"
        + "\n".join(lines)
    )


# ─── Core AI Agent ────────────────────────────────────────────────────────────

def get_medical_diagnosis(
    llm_id:        str,
    query:         str,
    allow_search:  bool,
    system_prompt: str,
    provider:      str,
    patient_info:  dict = None,
    max_retries:   int  = 2,
) -> str:
    """
    Run the medical diagnosis AI agent.

    Args:
        llm_id:        Model name string (e.g. 'llama3-70b-8192')
        query:         Symptom query built by analyze_symptoms()
        allow_search:  Enable Tavily web search tool
        system_prompt: Override system instructions (uses DEFAULT if None/empty)
        provider:      'Groq' or 'OpenAI'
        patient_info:  Optional dict of patient clinical data
        max_retries:   Retry count on transient errors (ENHANCEMENT)

    Returns:
        AI response string
    """
    # FIX 2: Always use DEFAULT if no prompt provided
    effective_prompt = system_prompt if system_prompt and system_prompt.strip() else DEFAULT_MEDICAL_PROMPT

    # ── Initialize LLM ──
    if provider == "Groq":
        llm = ChatGroq(model=llm_id, temperature=0.3)
    elif provider == "OpenAI":
        llm = ChatOpenAI(model=llm_id, temperature=0.3)
    else:
        raise ValueError(f"Unsupported provider: {provider}. Use 'Groq' or 'OpenAI'")

    # ── Setup Tools ──
    tools = []
    if allow_search:
        if not TAVILY_API_KEY:
            raise ValueError("TAVILY_API_KEY not set in .env — cannot enable web search")
        tools.append(TavilySearchResults(max_results=5))

    # ── Build Enhanced Query with Patient Context ──
    patient_context = build_patient_context(patient_info)

    if patient_context:
        enhanced_query = (
            f"{patient_context}\n\n"
            f"═══════════════════════════════════\n"
            f"CHIEF COMPLAINT / SYMPTOMS\n"
            f"═══════════════════════════════════\n"
            f"{query}"
        )
    else:
        enhanced_query = query

    # ── Create Agent ──
    # FIX 1: Only pass tools if non-empty; create_react_agent handles empty list fine
    # but being explicit avoids edge-case issues in some langgraph versions
    agent = create_react_agent(
        model=llm,
        tools=tools,
    )

    state = {
        "messages": [
            SystemMessage(content=effective_prompt),
            HumanMessage(content=enhanced_query),
        ]
    }

    # ── Invoke with Retry Logic (ENHANCEMENT) ──
    last_error = None
    for attempt in range(max_retries + 1):
        try:
            response  = agent.invoke(state)
            messages  = response.get("messages", [])
            ai_messages = [msg.content for msg in messages if isinstance(msg, AIMessage)]

            if not ai_messages:
                # FIX 3: Better error message instead of silent empty return
                return "⚠️ The AI agent did not return a response. Please try again or switch models."

            return ai_messages[-1]

        except Exception as e:
            last_error = e
            if attempt < max_retries:
                wait = 2 ** attempt  # exponential backoff: 1s, 2s
                print(f"⚠️  AI agent attempt {attempt+1} failed: {e}. Retrying in {wait}s...")
                time.sleep(wait)
            else:
                raise RuntimeError(f"AI agent failed after {max_retries + 1} attempts: {last_error}")


# ─── Symptom Query Builder ────────────────────────────────────────────────────

def analyze_symptoms(
    symptoms: list,
    severity: str = "Moderate",
    duration: str = None,
) -> str:
    """
    ENHANCEMENT: Build a richer structured symptom query for the AI agent.
    """
    if not symptoms:
        raise ValueError("At least one symptom is required")

    symptom_count = len(symptoms)
    symptom_text  = ", ".join(symptoms)

    query = (
        f"Chief Complaint: Patient presents with {symptom_count} symptom(s) "
        f"(overall severity: {severity}): {symptom_text}."
    )

    if duration:
        query += f" Duration of symptoms: {duration}."

    query += (
        "\n\nPlease provide a full clinical assessment including:\n"
        "1. Differential diagnosis (ranked by likelihood with ICD-10 codes)\n"
        "2. Treatment and prescription recommendations (OTC and Rx)\n"
        "3. Medications to avoid\n"
        "4. Recommended diagnostic tests\n"
        "5. Home care and lifestyle recommendations\n"
        "6. Urgency level assessment\n"
    )

    return query


# ─── Test Block ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    test_query = analyze_symptoms(
        symptoms=["severe headache", "high fever", "neck stiffness", "photophobia"],
        severity="Severe",
        duration="12 hours",
    )
    print("Test Query:")
    print(test_query)
    print("\nPatient Context Test:")
    ctx = build_patient_context({
        "age": 35, "gender": "Male", "weight": 80, "height": 175,
        "allergies": "Penicillin", "medical_history": "Hypertension"
    })
    print(ctx)
